---
- name: Clone the image repo
  ansible.builtin.git:
    repo: 'https://www.github.com/networkboot/docker-dhcpd'
    dest: "{{ repo_path }}"
- name: Build the image
  containers.podman.podman_image:
    name: "{{ image }}"
    path: "{{ repo_path }}"
    username: "{{docker_io_username}}"
    password: "{{docker_io_password}}"
  become: true
- name: Set up data directory
  ansible.builtin.file:
    path: "{{ data_directory }}"
    state: directory
  become: true
- name: Create config file
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: "{{ data_directory }}/dhcpd.conf"
  notify: Restart dhcpd
  become: true
- name: Install service
  ansible.builtin.template:
    src: dhcpd.service.j2
    dest: /etc/systemd/system/dhcpd.service
  register: service_file
  become: true
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: service_file is succeeded
  become: true
- name: Enable service
  ansible.builtin.systemd:
    name: dhcpd
    enabled: "{{ enabled }}"
    state: "{{ state }}"
  become: true
