---
- name: Set up data directories
  ansible.builtin.file:
    path: "{{ data_directory }}/{{ service_name }}/data"
    state: directory
  become: true
- name: Add env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ data_directory }}/{{ service_name }}/.env"
    mode: 0600
  when: lookup('ansible.builtin.vars', service_name + '_envvars', default='') != ''
  become: true
  notify: Restart service
- name: Install service
  ansible.builtin.template:
    src: "{{ service_name }}.service.j2"
    dest: /etc/systemd/system/{{ service_name }}.service
    mode: 0644
    owner: root
    group: root
  register: service_file
  become: true
  notify: Restart service
- name: Add Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ data_directory }}/{{ service_name }}/Caddyfile"
    mode: 0600
  become: true
  notify: Restart service
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: service_file is succeeded
  become: true
- name: Enable service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    enabled: "{{ enabled }}"
    state: "{{ state }}"
  become: true
