---
- name: Add service file
  template:
    src: pihole.service.j2
    dest: /etc/systemd/system/pihole.service
    mode: 0644
    owner: root
    group: root
  become: true
- name: Set up data directory
  ansible.builtin.file:
    path: "{{ data_directory }}"
    state: directory
  become: true
- name: Copy env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ data_directory}}/.env"
  become: true
- name: Copy dnsmasq files
  ansible.builtin.copy:
    src: files/dnsmasq.d/
    dest: "{{ data_directory }}/dnsmasq/"
  become: true
- name: Set up etc data directory
  ansible.builtin.file:
    path: "{{ data_directory }}/etc"
    state: directory
  become: true
- name: Copy hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: "{{ data_directory }}/etc/hosts"
  become: true
- name: Install service
  ansible.builtin.template:
    src: pihole.service.j2
    dest: /etc/systemd/system/pihole.service
  register: service_file
  become: true
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: service_file is succeeded
  become: true
- name: Enable service
  ansible.builtin.systemd:
    name: pihole
    enabled: "{{ enabled }}"
    state: "{{ state }}"
  become: true
